import type { DropdownOption } from "@/components/ui/searchable-dropdown";

export const US_STATES: DropdownOption[] = [
  { label: "Texas", value: "TX" },
  { label: "Utah", value: "UT" },
  { label: "California", value: "CA" },
  { label: "Florida", value: "FL" },
  { label: "New York", value: "NY" },
  { label: "Arizona", value: "AZ" },
  { label: "New Jersey", value: "NJ" },
  { label: "Massachusetts", value: "MA" },
  { label: "Georgia", value: "GA" },
  { label: "Pennsylvania", value: "PA" },
  { label: "Virginia", value: "VA" },
  { label: "Colorado", value: "CO" },
  { label: "Washington", value: "WA" },
  { label: "Illinois", value: "IL" },
  { label: "South Carolina", value: "SC" },
  { label: "Kentucky", value: "KY" },
  { label: "North Carolina", value: "NC" },
  { label: "Connecticut", value: "CT" },
  { label: "Nebraska", value: "NE" },
  { label: "Michigan", value: "MI" },
  { label: "Ohio", value: "OH" },
  { label: "Maryland", value: "MD" },
  { label: "Indiana", value: "IN" },
  { label: "Missouri", value: "MO" },
  { label: "Nevada", value: "NV" },
  { label: "Idaho", value: "ID" },
  { label: "Tennessee", value: "TN" },
  { label: "Oregon", value: "OR" },
  { label: "Iowa", value: "IA" },
  { label: "New Hampshire", value: "NH" },
  { label: "Arkansas", value: "AR" },
  { label: "Louisiana", value: "LA" },
  { label: "Montana", value: "MT" },
  { label: "Oklahoma", value: "OK" },
  { label: "Alaska", value: "AK" },
  { label: "New Mexico", value: "NM" },
  { label: "Wisconsin", value: "WI" },
  { label: "Minnesota", value: "MN" },
  { label: "North Dakota", value: "ND" },
  { label: "Mississippi", value: "MS" },
  { label: "Alabama", value: "AL" },
  { label: "West Virginia", value: "WV" },
  { label: "Wyoming", value: "WY" },
  { label: "Delaware", value: "DE" },
  { label: "Kansas", value: "KS" },
  { label: "Maine", value: "ME" },
  { label: "Rhode Island", value: "RI" },
];
