/**
 * core-catalog.ts — the 19 core treatments and 14 core concerns, and the map
 * from every retired slug to the core entry that replaced it.
 *
 * GENERATED on 2026-09-06. The generator (generate-core-catalog.ts) and its
 * inputs (core-map.json, plus the pre-reduction CSVs it derives the redirects
 * from) are bulk run artifacts and live OUTSIDE this repo, at
 * ../medspa-map-archive/one-time-scripts/ — see that directory's README.
 *
 * So treat this file as source: edit it deliberately, and then run
 *   bun --env-file=.env scripts/verify-core-links.ts
 * which asserts it matches the live database exactly (19 + 14, nothing extra),
 * that every retired slug still redirects to an active row, and that no
 * hardcoded /search link in src/ points at a slug that no longer exists.
 *
 * The catalog was reduced on 2026-09-06 from 966 services / 191 concerns to
 * these 33 entries, because a long tail of near-unique treatments meant most
 * specific searches returned "0 Practices Found". Nothing was deleted: the
 * retired rows are still in the database with is_active = false, and every
 * clinic_services.raw_name still holds the verbatim text scraped from the
 * clinic's own site.
 *
 * LEGACY_TREATMENT_REDIRECT / LEGACY_CONCERN_REDIRECT exist so that no link
 * ever dies. Old URLs, indexed search pages, blog CTAs and anything a user
 * typed before the reduction ("Morpheus8", "CoolSculpting", "Hyperpigmentation")
 * still resolve — to the core entry that now covers them. Only the 33 are
 * OFFERED anywhere in the UI; all 1,157 former names remain UNDERSTOOD.
 *
 * The 19 and 14 are flat and independent. In particular Botox and Dysport are
 * separate entries: the historical `dysport -> botox` alias in canonical.ts was
 * removed deliberately when this list was adopted.
 */

export type CoreEntry = { slug: string; name: string };

export const CORE_TREATMENTS: readonly CoreEntry[] = [
  { slug: "botox", name: "Botox®" },
  { slug: "dysport", name: "Dysport®" },
  { slug: "dermal-fillers", name: "Dermal Fillers" },
  { slug: "lip-fillers", name: "Lip Fillers" },
  { slug: "sculptra", name: "Sculptra®" },
  { slug: "prp-prf", name: "PRP / PRF Therapy" },
  { slug: "microneedling", name: "Microneedling" },
  { slug: "rf-microneedling", name: "RF Microneedling" },
  { slug: "chemical-peels", name: "Chemical Peels" },
  { slug: "facials", name: "Facials" },
  { slug: "hydrafacial", name: "HydraFacial®" },
  { slug: "laser-treatments", name: "Laser Treatments" },
  { slug: "laser-hair-removal", name: "Laser Hair Removal" },
  { slug: "laser-skin-resurfacing", name: "Laser Skin Resurfacing" },
  { slug: "ipl-photofacial", name: "IPL Photofacial" },
  { slug: "body-contouring", name: "Body Contouring" },
  { slug: "medical-weight-loss", name: "Medical Weight Loss" },
  { slug: "iv-therapy", name: "IV Therapy" },
  { slug: "hair-restoration", name: "Hair Restoration" },
  { slug: "cryotherapy", name: "Cryotherapy" },
  { slug: "red-light-therapy", name: "Red Light Therapy" },
  { slug: "hormone-therapy", name: "Hormone Therapy" },
] as const;

export const CORE_CONCERNS: readonly CoreEntry[] = [
  { slug: "wrinkles", name: "Wrinkles" },
  { slug: "fine-lines", name: "Fine Lines" },
  { slug: "pigmentation", name: "Pigmentation" },
  { slug: "dark-spots", name: "Dark Spots" },
  { slug: "melasma", name: "Melasma" },
  { slug: "sun-damage", name: "Sun Damage" },
  { slug: "uneven-skin-tone", name: "Uneven Skin Tone" },
  { slug: "uneven-skin-texture", name: "Uneven Skin Texture" },
  { slug: "acne", name: "Acne" },
  { slug: "acne-scars", name: "Acne Scars" },
  { slug: "veins", name: "Veins" },
  { slug: "skin-laxity", name: "Skin Laxity" },
  { slug: "facial-volume-loss", name: "Facial Volume Loss" },
  { slug: "hair-loss", name: "Hair Loss" },
] as const;

export const CORE_TREATMENT_SLUGS: readonly string[] = CORE_TREATMENTS.map((t) => t.slug);
export const CORE_CONCERN_SLUGS: readonly string[] = CORE_CONCERNS.map((c) => c.slug);

/** Retired treatment slug -> the core treatment that absorbed it. */
export const LEGACY_TREATMENT_REDIRECT: Readonly<Record<string, string>> = {
  "2940-erbium-yag-laser": "laser-skin-resurfacing",
  "a-list-facial": "facials",
  "accutite": "body-contouring",
  "acne-facial": "facials",
  "activefx": "laser-skin-resurfacing",
  "advanced-microneedling-treatments": "microneedling",
  "advatx": "laser-treatments",
  "aerolase-neoelite-laser": "laser-treatments",
  "aerolase-neoskin-rejuvenation-tightening": "laser-treatments",
  "aerolase-treatment": "laser-treatments",
  "agnes-precision-rf": "rf-microneedling",
  "allure-signature-express-facial": "facials",
  "allure-signature-facial": "facials",
  "alma-ted-hair-restoration-treatment": "hair-restoration",
  "alora-glow-microchanneling": "microneedling",
  "anti-aging-facial": "facials",
  "apex-signature-facial": "facials",
  "aquafacials": "hydrafacial",
  "aquafirm-facials": "facials",
  "aquafirme-medical-facial": "facials",
  "aquafirmexs-body-sculpting": "body-contouring",
  "aquafirmexs-facial": "facials",
  "arabella-gold-infusion": "facials",
  "av-li-cellulite-treatment": "body-contouring",
  "aveli-for-cellulite": "body-contouring",
  "avli-cellulite-treatment": "body-contouring",
  "b-12-lipotropic-injections": "medical-weight-loss",
  "back-facial": "facials",
  "bbl": "ipl-photofacial",
  "bbl-hair-reduction": "laser-hair-removal",
  "bela-md": "facials",
  "belamd-facial": "facials",
  "bellafill": "dermal-fillers",
  "belotero": "dermal-fillers",
  "belotero-balance": "dermal-fillers",
  "benev-exosome-therapy": "prp-prf",
  "biofiller": "dermal-fillers",
  "biorepeel": "chemical-peels",
  "biorepeelcl3": "chemical-peels",
  "biostimulators": "sculptra",
  "body-sculpting": "body-contouring",
  "bodytite": "body-contouring",
  "botox-and-fillers": "botox",
  "brightening-facial": "facials",
  "carbon-hollywood-facial": "laser-treatments",
  "carbon-laser-facial": "laser-treatments",
  "carbon-wave-cellulite-treatment": "body-contouring",
  "cavitation": "body-contouring",
  "cellenis-derma-prp": "prp-prf",
  "cellulaze": "body-contouring",
  "cellulite-laser-treatment": "body-contouring",
  "cheek-and-chin-enhancement": "dermal-fillers",
  "cheek-filler": "dermal-fillers",
  "cheeky-blackout-laser-facial": "laser-treatments",
  "cheeky-halo-laser-facial": "laser-skin-resurfacing",
  "chemical-peel": "chemical-peels",
  "chemical-peel-alastin": "chemical-peels",
  "chin-balancing": "dermal-fillers",
  "chin-fat-removal": "body-contouring",
  "chin-filler": "dermal-fillers",
  "chin-sculpting": "body-contouring",
  "clay-facials": "facials",
  "clear-bright": "laser-treatments",
  "clear-brilliant": "laser-skin-resurfacing",
  "clearlift": "laser-skin-resurfacing",
  "clearlift-fractional-laser": "laser-skin-resurfacing",
  "clearv-laser-treatments": "laser-treatments",
  "co2-facial": "facials",
  "co2-laser": "laser-skin-resurfacing",
  "co2lift": "laser-skin-resurfacing",
  "collagen-biostimulators-sculptra-prx-t33": "sculptra",
  "collagen-induction-therapy": "microneedling",
  "combo-lipo-skinny-b6-b12-injections": "medical-weight-loss",
  "combo-lipo-skinny-b6-b12-iv-therapy": "iv-therapy",
  "combo-lipo-skinnyb6b12-injections": "medical-weight-loss",
  "combo-lipo-skinnyb6b12-iv-therapy": "iv-therapy",
  "combo-pack-injections": "iv-therapy",
  "combo-pack-iv-therapy": "iv-therapy",
  "contour-trl": "chemical-peels",
  "coolpeel": "laser-skin-resurfacing",
  "coolpeel-co2-laser": "laser-skin-resurfacing",
  "coolpeel-laser": "laser-skin-resurfacing",
  "coolsculpting": "body-contouring",
  "coolsculpting-elite": "body-contouring",
  "cooltone": "body-contouring",
  "cosmelan-treatment": "chemical-peels",
  "cryo-slimming": "body-contouring",
  "cryo-t-shock": "body-contouring",
  "cryocorrect": "body-contouring",
  "cryofacial": "facials",
  "cryosculpt": "body-contouring",
  "cryoskin": "body-contouring",
  "daxxify": "botox",
  "deep-hydration": "iv-therapy",
  "deep-hydration-facial": "facials",
  "dep-rejuvenation-facial": "facials",
  "dermabrasion": "facials",
  "dermal-filler-correction": "dermal-fillers",
  "dermal-fillers-and-biostimulators": "dermal-fillers",
  "dermamelan-intimate-treatment": "chemical-peels",
  "dermaplane": "facials",
  "dermaplaning": "facials",
  "dermav": "facials",
  "diamond-microdermabrasion-facial": "facials",
  "diamondglow": "facials",
  "diamondglow-facial": "facials",
  "diolite-laser": "laser-treatments",
  "diosculpt-laser-body-contouring": "body-contouring",
  "dmk-enzyme-therapy": "facials",
  "elite-iq": "laser-treatments",
  "elluminate-laser-facial": "ipl-photofacial",
  "elos-laser-system": "laser-treatments",
  "emerald-laser": "body-contouring",
  "ems-sculpting": "body-contouring",
  "emsculpt": "body-contouring",
  "emsculpt-neo": "body-contouring",
  "emsculpt-neo-and-emsella": "body-contouring",
  "emshape-neo": "body-contouring",
  "emtone": "body-contouring",
  "endosphere-treatment": "body-contouring",
  "endura-shot": "iv-therapy",
  "energy-boost-iv-therapy": "iv-therapy",
  "erbium-deep-laser-resurfacing": "laser-skin-resurfacing",
  "erbium-laser-peel": "laser-skin-resurfacing",
  "erbium-laser-skin-resurfacing": "laser-skin-resurfacing",
  "erbium-yag": "laser-skin-resurfacing",
  "essence-signature-facial": "facials",
  "evolvex": "body-contouring",
  "evolvex-body-contouring": "body-contouring",
  "excel-v": "laser-treatments",
  "exfoliation": "facials",
  "exosomes": "prp-prf",
  "exosomes-facial": "prp-prf",
  "exosomes-for-collagen-repair": "prp-prf",
  "exosomes-stem-cell-derived": "prp-prf",
  "eyebrow-filler": "dermal-fillers",
  "eyelid-tear-trough-filler": "dermal-fillers",
  "eyelidtear-trough-filler": "dermal-fillers",
  "ez-gel-biofiller": "prp-prf",
  "ez-gel-prf": "prp-prf",
  "ez-gel-prf-natural-fillers": "prp-prf",
  "ez-gel-prf-prp": "prp-prf",
  "facetite": "body-contouring",
  "facial-balancing": "dermal-fillers",
  "facial-contouring": "dermal-fillers",
  "facial-contouring-with-agnes-ultra": "rf-microneedling",
  "facial-dermabrasion": "facials",
  "facial-fillers": "dermal-fillers",
  "facial-rejuvenation-with-natural-growth-factors": "prp-prf",
  "facial-services": "facials",
  "fat-burner-shots": "medical-weight-loss",
  "fat-dissolver": "body-contouring",
  "fat-dissolving": "body-contouring",
  "fat-dissolving-injections": "body-contouring",
  "filler-dissolve": "dermal-fillers",
  "filler-treatments": "dermal-fillers",
  "fillers-with-prp": "dermal-fillers",
  "flexsure": "body-contouring",
  "forehead-filler": "dermal-fillers",
  "fotona-4d-facelift": "laser-treatments",
  "fotona-timewalker-laser": "laser-treatments",
  "fractional-laser": "laser-skin-resurfacing",
  "frax-laser": "laser-skin-resurfacing",
  "fraxel": "laser-skin-resurfacing",
  "full-facial-balancing": "dermal-fillers",
  "genius-underarm-sweating": "rf-microneedling",
  "gentlemax-pro-laser": "laser-hair-removal",
  "glass-facial": "facials",
  "glassy-skin-facial": "facials",
  "glo2facial": "facials",
  "glow-facial": "facials",
  "glp-1-peptides": "medical-weight-loss",
  "glp-1-weight-loss-injections": "medical-weight-loss",
  "glutathione": "iv-therapy",
  "glutathione-boost-iv-add-on": "iv-therapy",
  "glutathione-therapy": "iv-therapy",
  "glutathione-treatments": "iv-therapy",
  "glycolic-peel": "chemical-peels",
  "hair-growth": "hair-restoration",
  "hair-regeneration": "hair-restoration",
  "hair-regrowth": "hair-restoration",
  "hair-restoration-with-derive": "hair-restoration",
  "hair-restoration-with-natural-growth-factors": "hair-restoration",
  "hair-transplant": "hair-restoration",
  "halo": "laser-skin-resurfacing",
  "hand-filler": "dermal-fillers",
  "hand-rejuvenation": "dermal-fillers",
  "hangover-iv-therapy": "iv-therapy",
  "hcg-diet-support": "medical-weight-loss",
  "headache-relief-iv-therapy": "iv-therapy",
  "helix-co2-laser-treatment": "laser-skin-resurfacing",
  "helix-laser-treatment": "laser-treatments",
  "high-dose-vitamin-c-iv-therapy": "iv-therapy",
  "hollywood-laser": "laser-treatments",
  "hollywood-laser-facial": "laser-treatments",
  "hollywood-spectra-laser-peel": "laser-treatments",
  "hydra-needle-dermal-infusion": "microneedling",
  "hydra-perfectionmd": "facials",
  "hydrafacial-keravive": "hair-restoration",
  "hydrating-facial": "facials",
  "hydrodiamond-exfoliation-facial": "facials",
  "hydroglow-facials": "facials",
  "hyperdilute-radiesse": "dermal-fillers",
  "hyperdilute-radiesse-body": "dermal-fillers",
  "hyperdilute-radiesse-face": "dermal-fillers",
  "hyperdiluted-radiesse": "dermal-fillers",
  "icon-laser": "laser-treatments",
  "immune-spark-iv-add-on": "iv-therapy",
  "immunity-boost-iv-therapy": "iv-therapy",
  "immunity-boost-therapy": "iv-therapy",
  "injectables-for-volume-loss": "dermal-fillers",
  "injectables-for-wrinkles": "botox",
  "inner-beauty-booster-iv-therapy": "iv-therapy",
  "intense-pulse-light": "ipl-photofacial",
  "intimate-lightening-body-peel": "chemical-peels",
  "intraceuticals-oxygen-facial": "facials",
  "ipl": "ipl-photofacial",
  "ipl-acne-treatment": "ipl-photofacial",
  "ipl-facial": "ipl-photofacial",
  "ipl-laser": "ipl-photofacial",
  "ipl-laser-treatment": "ipl-photofacial",
  "ipl-lumecca": "ipl-photofacial",
  "ipl-nafl-photofacial": "ipl-photofacial",
  "iplnafl-photofacial": "ipl-photofacial",
  "iv-vitamin-therapy": "iv-therapy",
  "jawline-chin-neck-filler": "dermal-fillers",
  "jawline-filler": "dermal-fillers",
  "jawlinechinneck-filler": "dermal-fillers",
  "jeuveau": "botox",
  "juv-derm-ultra": "dermal-fillers",
  "juv-derm-volbella": "lip-fillers",
  "juv-derm-voluma": "dermal-fillers",
  "juvashape": "body-contouring",
  "juvderm-ultra": "dermal-fillers",
  "juvderm-volbella": "lip-fillers",
  "juvderm-voluma": "dermal-fillers",
  "juvederm": "dermal-fillers",
  "juvederm-and-restylane": "dermal-fillers",
  "juvederm-collection": "dermal-fillers",
  "juvederm-dermal-fillers": "dermal-fillers",
  "juvederm-ultra-plus": "dermal-fillers",
  "juvederm-voluma": "dermal-fillers",
  "k-8x-ultimate-dermal-renewal-facial": "facials",
  "keralase-hair-treatment": "hair-restoration",
  "keravive": "hair-restoration",
  "keravive-scalp-therapy": "hair-restoration",
  "keravive-scalp-treatment": "hair-restoration",
  "kids-and-teen-facials": "facials",
  "kybella": "body-contouring",
  "l-carnitine-therapy": "medical-weight-loss",
  "l-glutathione-iv-therapy": "iv-therapy",
  "lasemd-ultra": "laser-skin-resurfacing",
  "laser-acne-treatment": "laser-treatments",
  "laser-dermabrasion": "laser-skin-resurfacing",
  "laser-excel-v": "laser-treatments",
  "laser-eye-rejuvenation": "laser-treatments",
  "laser-facial-with-the-motus-pro": "laser-treatments",
  "laser-facials": "facials",
  "laser-genesis": "laser-treatments",
  "laser-hair-restoration": "hair-restoration",
  "laser-lip-rejuvenation": "laser-skin-resurfacing",
  "laser-lipo": "body-contouring",
  "laser-lipo-thigh": "body-contouring",
  "laser-lipolysis": "body-contouring",
  "laser-liposculpture": "body-contouring",
  "laser-nail-fungal-treatment": "laser-treatments",
  "laser-peel": "laser-skin-resurfacing",
  "laser-pigment-removal": "laser-treatments",
  "laser-rejuvenation": "laser-treatments",
  "laser-scar-reduction": "laser-skin-resurfacing",
  "laser-scar-removal": "laser-skin-resurfacing",
  "laser-skin-rejuvenation": "laser-treatments",
  "laser-skin-treatments": "laser-treatments",
  "laser-tattoo-removal": "laser-treatments",
  "laser-therapy": "laser-treatments",
  "laser-toenail-fungus-removal": "laser-treatments",
  "laser-toning-hyperpigmentation": "laser-treatments",
  "letybo": "botox",
  "light-bright-photo-facial": "ipl-photofacial",
  "light-therapy-for-hair-restoration": "hair-restoration",
  "lip-augmentation": "lip-fillers",
  "lip-enhancement": "lip-fillers",
  "lip-filler": "lip-fillers",
  "lip-flip": "lip-fillers",
  "lip-flip-filler": "lip-fillers",
  "lip-injections": "lip-fillers",
  "lip-treatment": "lip-fillers",
  "liplase-by-fotona": "laser-treatments",
  "lipo-360": "body-contouring",
  "lipo-mino-injections": "medical-weight-loss",
  "lipo-skinny-injections": "medical-weight-loss",
  "lipodissolve": "body-contouring",
  "lipolysis": "body-contouring",
  "lipolysis-for-cellulite": "body-contouring",
  "lipotropic-injections": "medical-weight-loss",
  "liquid-bbl": "dermal-fillers",
  "liquid-face-lift": "dermal-fillers",
  "liquid-gold-facial": "facials",
  "liquid-lipo": "body-contouring",
  "liquid-nose-job": "dermal-fillers",
  "liquid-rhinoplasty": "dermal-fillers",
  "lumecca": "ipl-photofacial",
  "lumecca-ipl": "ipl-photofacial",
  "lumilift-signature-facial": "facials",
  "luxury-iv-hydration": "iv-therapy",
  "masseter-tmj-treatment": "botox",
  "massetertmj-treatment": "botox",
  "medical-facial-rejuvenation": "facials",
  "melasma-laser-facial": "laser-treatments",
  "men-lip-flip-with-plla-or-botox": "lip-fillers",
  "men-s-custom-facial": "facials",
  "mens-custom-facial": "facials",
  "methylcobalamin-b-12-iv-therapy": "iv-therapy",
  "methylcobalamin-b-12-therapy": "iv-therapy",
  "microchanneling": "microneedling",
  "microdermabrasion": "facials",
  "microdermabrasion-facial": "facials",
  "microglow": "facials",
  "microinfusion-facial": "facials",
  "microneedling-prf-under-eye-rejuvenation": "prp-prf",
  "microneedling-with-anteage": "microneedling",
  "microneedling-with-ariessence": "microneedling",
  "microneedling-with-exosomes": "prp-prf",
  "microneedling-with-human-growth-factor": "microneedling",
  "microneedling-with-natural-growth-factors": "microneedling",
  "microneedling-with-prf": "prp-prf",
  "microneedling-with-prp": "prp-prf",
  "microneedling-with-skinpen": "microneedling",
  "minoxidil-hair-restoration": "hair-restoration",
  "morpheus8": "rf-microneedling",
  "morpheus8-body": "rf-microneedling",
  "morpheus8-skin-remodeling": "rf-microneedling",
  "motus-az-laser-treatment": "laser-hair-removal",
  "moxi": "laser-skin-resurfacing",
  "moxi-bbl-heroic-treatment": "ipl-photofacial",
  "moxi-laser-resurfacing": "laser-skin-resurfacing",
  "nad": "iv-therapy",
  "nad-injection": "iv-therapy",
  "nad-iv-drip-therapy": "iv-therapy",
  "nad-iv-therapy": "iv-therapy",
  "nad-subq-injections": "iv-therapy",
  "nad-therapy": "iv-therapy",
  "nad-vitamin-therapy": "iv-therapy",
  "nano-arctic-peel": "chemical-peels",
  "nanopeel-and-micropeel": "chemical-peels",
  "nasolabial-fold-fillers": "dermal-fillers",
  "natural-growth-factor-injections": "prp-prf",
  "natural-growth-factor-injections-for-hair": "hair-restoration",
  "natural-growth-factors-added-to-fillers": "dermal-fillers",
  "ndyag-laser": "laser-treatments",
  "nefertiti-neck-lift": "botox",
  "neoclear-acne-treatment": "laser-treatments",
  "neogen-psr-skin-rejuvenation": "laser-skin-resurfacing",
  "neogen-skin-regeneration-treatment": "laser-skin-resurfacing",
  "niagen-iv-infusions": "iv-therapy",
  "non-surgical-bbl": "body-contouring",
  "non-surgical-butt-lift": "body-contouring",
  "non-surgical-rhinoplasty": "dermal-fillers",
  "nordlys-ellipse-ipl": "ipl-photofacial",
  "nutrafol": "hair-restoration",
  "nutrient-boosts": "iv-therapy",
  "opus": "laser-skin-resurfacing",
  "opus-mini": "laser-skin-resurfacing",
  "opus-plasma": "rf-microneedling",
  "oxygen-facial": "facials",
  "oxygen-infusion": "facials",
  "pca-peels": "chemical-peels",
  "pcdc-injections": "body-contouring",
  "pdgf-bb-injectable-growth-factors": "prp-prf",
  "pdgf-therapy": "prp-prf",
  "pdgf-treatments": "prp-prf",
  "photofacial": "ipl-photofacial",
  "photoglow": "ipl-photofacial",
  "physiq-body-contouring": "body-contouring",
  "pico-iv-for-pain-management": "iv-therapy",
  "pico-laser": "laser-treatments",
  "pico-laser-treatment": "laser-treatments",
  "picocare-majesty-brightening-laser": "laser-treatments",
  "picocare-majesty-pigment-correction": "laser-treatments",
  "picocare-majesty-pore-texture-refinement": "laser-treatments",
  "picocare-majesty-scar-repair": "laser-treatments",
  "picosure": "laser-treatments",
  "picosure-laser": "laser-treatments",
  "picoway": "laser-treatments",
  "picoway-resolve": "laser-skin-resurfacing",
  "pixel8-rf": "rf-microneedling",
  "plasma-fillers": "prp-prf",
  "plasma-gel-treatment": "prp-prf",
  "platelet-rich-plasma-prp-platelet-rich-fibrin-prf": "prp-prf",
  "platinum-hydrafacial": "hydrafacial",
  "polynucleotide-salmon-dna-microneedling": "microneedling",
  "ppx-autologous-exosomes": "prp-prf",
  "prf-ez-gel-natural-filler": "prp-prf",
  "prf-facial-rejuvenation": "prp-prf",
  "prf-for-hair-loss": "hair-restoration",
  "prf-hair-restoration": "hair-restoration",
  "prf-microneedling": "prp-prf",
  "prf-under-eye-treatment": "prp-prf",
  "prfm-plasma-facelift": "prp-prf",
  "profound-rf": "rf-microneedling",
  "profractional": "laser-skin-resurfacing",
  "prp-and-prf-therapy": "prp-prf",
  "prp-exosome": "prp-prf",
  "prp-facial": "prp-prf",
  "prp-for-hair": "hair-restoration",
  "prp-hair-restoration": "hair-restoration",
  "prp-hair-restoration-therapy": "hair-restoration",
  "prp-injections": "prp-prf",
  "prp-joint-injections": "prp-prf",
  "prp-microneedling": "prp-prf",
  "prp-prf-2": "prp-prf",
  "prp-prf-exosomes": "prp-prf",
  "prp-prf-hair-restoration": "hair-restoration",
  "prp-prf-injections": "prp-prf",
  "prp-prf-microneedling": "prp-prf",
  "prpexosome": "prp-prf",
  "prpprf-hair-restoration": "hair-restoration",
  "prpprf-injections": "prp-prf",
  "prx": "chemical-peels",
  "prx-derm-perfexion": "chemical-peels",
  "prx-derm-perfexion-glow": "chemical-peels",
  "prx-peel": "chemical-peels",
  "prx-treatment": "chemical-peels",
  "pulse-dye-laser": "laser-treatments",
  "purifying-facial": "facials",
  "quench-iv-hydration-therapy": "iv-therapy",
  "qwo-cellulite-treatment": "body-contouring",
  "radiesse": "dermal-fillers",
  "reboot-iv-therapy": "iv-therapy",
  "recovery-performance-iv-therapy": "iv-therapy",
  "redensity": "dermal-fillers",
  "regenerative-biologics-prf-prp": "prp-prf",
  "regenerative-biologics-prfprp": "prp-prf",
  "rejuvenate-restore-iv-therapy": "iv-therapy",
  "renuva": "dermal-fillers",
  "restylane": "dermal-fillers",
  "restylane-collection": "dermal-fillers",
  "restylane-contour": "dermal-fillers",
  "restylane-defyne": "dermal-fillers",
  "restylane-kysse": "lip-fillers",
  "restylane-lyft": "dermal-fillers",
  "resurfacing-pigment-laser-facial": "laser-skin-resurfacing",
  "resurfx": "laser-skin-resurfacing",
  "revanesse-versa": "dermal-fillers",
  "revlite-laser": "laser-treatments",
  "rf-microneedling-for-hair-growth": "hair-restoration",
  "rha": "dermal-fillers",
  "rosacea-laser-treatment": "laser-treatments",
  "safesculpt": "body-contouring",
  "salt-facial": "facials",
  "scalp-injections": "hair-restoration",
  "sciton-laser": "laser-treatments",
  "sciton-trl-profractional-laser-resurfacing": "laser-skin-resurfacing",
  "sculpsure": "body-contouring",
  "sculptra-butt-lift": "sculptra",
  "sculptra-butt-lift-non-surgical-bbl": "sculptra",
  "sculptra-buttocks-hip-contouring": "sculptra",
  "sculptra-radiesse-butt-lift": "sculptra",
  "selphyller-gel-ez-gel-prf-treatment": "prp-prf",
  "semaglutide": "medical-weight-loss",
  "sensitive-skin-facial": "facials",
  "signature-facial": "facials",
  "skin-booster": "dermal-fillers",
  "skin-brightening": "facials",
  "skin-tightening-laser": "laser-treatments",
  "skin-tightening-thigh": "body-contouring",
  "skinbetter-peel": "chemical-peels",
  "skinjuvenation": "facials",
  "skinny-shot-glp-1-weight-loss-injections": "medical-weight-loss",
  "skinny-shot-treatments": "medical-weight-loss",
  "skinpen": "microneedling",
  "skinpen-microneedling": "microneedling",
  "skintyte-laser-treatments": "laser-treatments",
  "skinvive": "dermal-fillers",
  "skinvive-by-juvederm": "dermal-fillers",
  "smartlipo": "body-contouring",
  "smaxel-co2-laser": "laser-skin-resurfacing",
  "stem-cell-and-exosome-therapy": "prp-prf",
  "stem-cell-exosome-therapy": "prp-prf",
  "stimulates-natural-hair-growth": "hair-restoration",
  "stomach-flu-reset-iv-therapy": "iv-therapy",
  "stretch-mark-laser": "laser-skin-resurfacing",
  "super-immune-recharger-iv-therapy": "iv-therapy",
  "sylfirm-x": "rf-microneedling",
  "sylfirm-x-rf-microneedling": "rf-microneedling",
  "t-shape-2": "body-contouring",
  "t-shape-2-body-facial-sculpting": "body-contouring",
  "tattoo-removal": "laser-treatments",
  "tear-trough-filler": "dermal-fillers",
  "telangiectasia-treatment": "laser-treatments",
  "temple-filler": "dermal-fillers",
  "temple-lift": "dermal-fillers",
  "tetra-co2-coolpeel": "laser-skin-resurfacing",
  "the-bloom-facial": "facials",
  "the-brightening-peel": "chemical-peels",
  "the-clarity-facial": "facials",
  "the-growth-factor-drip": "iv-therapy",
  "the-mega-root-iv-therapy": "iv-therapy",
  "the-perfect-derma-peel": "chemical-peels",
  "the-root-iv-therapy": "iv-therapy",
  "the-saltfacial": "facials",
  "the-shield-iv-therapy": "iv-therapy",
  "the-thrive-drip-iv-therapy": "iv-therapy",
  "thermavein": "laser-treatments",
  "threeforme": "laser-treatments",
  "tirzepatide": "medical-weight-loss",
  "tixel": "laser-skin-resurfacing",
  "tixel-skin-resurfacing": "laser-skin-resurfacing",
  "tmj-treatment": "botox",
  "topical-hair-growth-formulations": "hair-restoration",
  "tox-boost-iv-add-on": "iv-therapy",
  "toxbooster-treatment": "botox",
  "tri-immune-boost-injection": "iv-therapy",
  "trusculpt": "body-contouring",
  "trusculpt-id": "body-contouring",
  "ultra-wave-for-vascular-treatment": "laser-treatments",
  "ultraclear": "laser-skin-resurfacing",
  "ultralight-co2-laser": "laser-skin-resurfacing",
  "under-eye-prp-filler": "prp-prf",
  "vampire-facial": "prp-prf",
  "vampire-facial-microneedling-with-prp": "prp-prf",
  "vampire-prp-hair-growth-scalp-rejuvenation": "hair-restoration",
  "vascular-laser-ktp": "laser-treatments",
  "vascular-laser-treatment": "laser-treatments",
  "vascular-lesion-redness-treatment": "laser-treatments",
  "vasculaze": "laser-treatments",
  "vaser-lipo": "body-contouring",
  "vbeam-laser": "laser-treatments",
  "venus-freeze": "body-contouring",
  "venus-legacy": "body-contouring",
  "versa": "dermal-fillers",
  "vi-peel": "chemical-peels",
  "vital-glow-iv-therapy": "iv-therapy",
  "vitali-facial": "facials",
  "vitamin-b12-injections": "iv-therapy",
  "vitamin-d-therapy": "iv-therapy",
  "vitamin-d-treatments": "iv-therapy",
  "vitamin-injections": "iv-therapy",
  "vitamin-shot-therapy": "iv-therapy",
  "xeomin": "botox",
  "xtrac-excimer-laser": "laser-treatments",
  "zeo-hair-restoration": "hair-restoration",
  "zo-stimulator-peel": "chemical-peels",
};

/** Retired concern slug -> the core concern that absorbed it. */
export const LEGACY_CONCERN_REDIRECT: Readonly<Record<string, string>> = {
  "acne-related-texture-irregularities": "uneven-skin-texture",
  "acne-scarring": "acne-scars",
  "age-spots": "dark-spots",
  "aging-concerns": "wrinkles",
  "aging-skin": "wrinkles",
  "broken-capillaries": "veins",
  "bunny-lines": "wrinkles",
  "cheek-definition": "facial-volume-loss",
  "congestion": "uneven-skin-texture",
  "crepey-skin": "skin-laxity",
  "crepey-texture": "skin-laxity",
  "crow-s-feet": "wrinkles",
  "crows-feet": "wrinkles",
  "dark-spots-melasma": "dark-spots",
  "double-chin": "skin-laxity",
  "double-chin-submental-fullness": "skin-laxity",
  "dull-skin": "uneven-skin-tone",
  "dullness": "uneven-skin-tone",
  "early-signs-of-aging": "wrinkles",
  "enlarged-pores": "uneven-skin-texture",
  "fine-lines-wrinkles": "wrinkles",
  "forehead-lines": "wrinkles",
  "freckles": "dark-spots",
  "frown-lines": "wrinkles",
  "hyperpigmentation": "pigmentation",
  "jowling": "skin-laxity",
  "jowls": "skin-laxity",
  "lip-lines": "wrinkles",
  "loose-sagging-skin": "skin-laxity",
  "marionette-lines": "wrinkles",
  "mild-laxity": "skin-laxity",
  "nasolabial-folds": "wrinkles",
  "neck-bands": "wrinkles",
  "platysma-vertical-neck-cords": "wrinkles",
  "port-wine-stains": "veins",
  "redness": "veins",
  "rosacea": "veins",
  "sagging-skin": "skin-laxity",
  "scars": "uneven-skin-texture",
  "scowl-lines-11s": "wrinkles",
  "skin-discoloration": "pigmentation",
  "skin-laxity-sagging": "skin-laxity",
  "skin-texture": "uneven-skin-texture",
  "sparse-brows": "hair-loss",
  "spider-veins": "veins",
  "thin-lips": "facial-volume-loss",
  "thinning-hair": "hair-loss",
  "under-eye-hollows": "facial-volume-loss",
  "uneven-tone": "uneven-skin-tone",
  "varicose-veins": "veins",
  "vascular-issues": "veins",
  "veiny-hands": "veins",
  "volume-loss": "facial-volume-loss",
  "wrinkle-softening": "wrinkles",
  "wrinkles-fine-lines": "wrinkles",
};

const norm = (s: string) => s.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/** Core treatment slug for a retired slug or name, or null. */
export function coreTreatmentFor(slugOrName: string): string | null {
  const n = norm(slugOrName);
  if (CORE_TREATMENT_SLUGS.includes(n)) return n;
  return LEGACY_TREATMENT_REDIRECT[n] ?? null;
}

/** Core concern slug for a retired slug or name, or null. */
export function coreConcernFor(slugOrName: string): string | null {
  const n = norm(slugOrName);
  if (CORE_CONCERN_SLUGS.includes(n)) return n;
  return LEGACY_CONCERN_REDIRECT[n] ?? null;
}
